admin:
  password: ${admin_password}

persistence:
  type: pvc
  enabled: true
  storageClassName: ${storage_class}
  accessModes:
    - ReadWriteOnce
  size: 2Gi

service:
  type: LoadBalancer

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingress:
  enabled: false

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    kubernetes:
      gnetId: 315
      revision: 3
      datasource: Prometheus

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: ${prometheus_endpoint}
        access: proxy
        isDefault: true
      - name: Loki
        type: loki
        url: ${loki_endpoint}
        access: proxy
      - name: Tempo
        type: tempo
        url: ${tempo_endpoint}
        access: proxy
        jsonData:
          tracesToLogs:
            datasourceUid: Loki
            tags: ['job', 'instance', 'pod', 'namespace']
            mappedTags: [{ key: 'service.name', value: 'service' }]
            spanStartTimeShift: '-1h'
            spanEndTimeShift: '1h'
            filterByTraceID: true
            filterBySpanID: false
          serviceMap:
            datasourceUid: prometheus

# plugins:
#   - grafana-piechart-panel
#   - grafana-clock-panel

serviceMonitor:
  enabled: false

sidecar:
  dashboards:
    enabled: false
    searchNamespace: ALL
