adminPassword: ${admin_password}

persistence:
  type: pvc
  enabled: true
  storageClassName: ${storage_class}
  accessModes:
    - ReadWriteOnce
  size: 10Gi

service:
  type: LoadBalancer

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingress:
  enabled: false

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    kubernetes:
      gnetId: 315
      revision: 3
      datasource: Prometheus

serviceMonitor:
  enabled: true

sidecar:
  dashboards:
    enabled: true
    searchNamespace: ALL
