tempo:
  repository: grafana/tempo
  pullPolicy: IfNotPresent
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 256m
      memory: 256Mi

  persistence:
    enabled: true
    storageClass: ${storage_class}
    size: 10Gi

  receivers:
    jaeger:
      protocols:
        grpc:
          endpoint: "0.0.0.0:14250"
        thrift_binary:
          endpoint: "0.0.0.0:6832"
        thrift_compact:
          endpoint: "0.0.0.0:6831"
        thrift_http:
          endpoint: "0.0.0.0:14268"
    zipkin:
      endpoint: "0.0.0.0:9411"
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
      wal:
        path: /var/tempo/wal

  serviceMonitor:
    enabled: true
    interval: 30s
    
  config:
    search_enabled: true
    metrics_generator_enabled: true

  multitenancy:
    enabled: false

  ingester:
    trace_idle_period: 30s
    max_block_duration: 5m
    complete_block_timeout: 5m

  compactor:
    compaction:
      block_retention: 168h # 7 days

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: "30s"

  service:
    annotations: {}

  serviceAccount:
    create: true
    annotations: {}
