loki:
  auth_enabled: false
  useTestSchema: true
  config: |
    auth_enabled: false
    server:
      http_listen_port: 3100

    common:
      path_prefix: /var/loki
      storage:
        filesystem:
          chunks_directory: /var/loki/chunks
      replication_factor: 1

singleBinary:
  replicas: 1

persistence:
  enabled: true
  storageClassName: ${storage_class}
  size: 5Gi
  accessModes:
    - ReadWriteOnce

monitoring:
  selfMonitoring:
    enabled: false
  lokiCanary:
    enabled: false
  serviceMonitor:
    enabled: false