loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  storage_config:
    filesystem:
      directory: /tmp/loki/chunks
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    retention_period: 48h
    ingestion_rate_mb: 4
    ingestion_burst_size_mb: 6
    max_global_streams_per_user: 5000
    max_query_length: 721h
    max_query_parallelism: 32
    max_streams_per_user: 0
    max_chunk_age: 2h
    chunk_target_size: 1536000
    chunk_retain_period: 30s
    max_cache_freshness_per_query: 10m
    split_queries_by_interval: 30m
  compactor:
    working_directory: /data/loki/boltdb-shipper-compactor
    shared_store: filesystem
    compaction_interval: 10m
    retention_enabled: true
    retention_delete_delay: 2h
    retention_delete_worker_count: 150
  ruler:
    enable_api: true
  auth_enabled: false
  chunk_store_config:
    max_look_back_period: 720h
  table_manager:
    retention_deletes_enabled: true
    retention_period: 48h
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "node-1"
    effect: "NoSchedule"
  - key: "dedicated"
    operator: "Equal"
    value: "node-2"
    effect: "NoSchedule"

minio:
  enabled: false
      
deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  persistence:
    storageClass: ${storage_class}
    accessModes:
      - ReadWriteOnce
    size: 20Gi
  # resources:
  #   requests:
  #     cpu: "1"
  #     memory: "2Gi"
  #   limits:
  #     cpu: "2"
  #     memory: "4Gi"

sidecar:
  image:
    repository: kiwigrid/k8s-sidecar
    tag: 1.30.0
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 100m
      memory: 100Mi

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

chunksCache:
  allocatedMemory: 500