loki:
  auth_enabled: false

  persistence:
    enabled: true
    storageClassName: ${storage_class}
    size: 5Gi
    accessModes:
      - ReadWriteOnce

  # resources:
  #   limits:
  #     cpu: "1"
  #     memory: 1Gi
  #   requests:
  #     cpu: 500m
  #     memory: 512Mi

  config:
    storage_config:
      filesystem:
        chunks_directory: /var/loki/chunks
    schema_config:
      configs:
        - from: "2023-01-01"
          store: boltdb-shipper
          object_store: filesystem
          schema: v12
          index:
            prefix: index_
            period: 24h

minio:
  enabled: false
      
deploymentMode: SingleBinary

singleBinary:
  replicas: 1

gateway:
  enabled: false

sidecar:
  image:
    repository: kiwigrid/k8s-sidecar
    tag: 1.30.0
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 100m
      memory: 100Mi

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

chunksCache:
  allocatedMemory: 500

monitoring:
  serviceMonitor:
    enabled: false
    metricsInstance:
      enabled: false

serviceMonitor:
  enabled: false

service:
  type: ClusterIP