apiVersion: v1
kind: Secret
metadata:
  name: todo-app-mongodb-secret
  namespace: dev
  labels:
    app.kubernetes.io/name: todo-application
    app.kubernetes.io/instance: dev
    app.kubernetes.io/part-of: todo-application
type: Opaque
stringData:
  host: "mongodb-0.mongodb.dev.svc.cluster.local"
  port: "27017"
  database: "todos"
  username: "${MONGODB_USERNAME}"
  password: "${MONGODB_PASSWORD}"