apiVersion: v1
kind: Secret
metadata:
  name: todo-app-mongodb-secret
  namespace: dev
  labels:
    app.kubernetes.io/name: todo-application
    app.kubernetes.io/instance: dev
    app.kubernetes.io/part-of: todo-application
type: Opaque
stringData:
  host: "mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb.dev.svc.cluster.local:27017/todos?authSource=admin"