---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: application-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: application
      app.kubernetes.io/instance: dev
      app.kubernetes.io/part-of: application
      app.kubernetes.io/managed-by: github-actions
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: application
        app.kubernetes.io/instance: dev
        app.kubernetes.io/part-of: application
        app.kubernetes.io/managed-by: github-actions
        app.kubernetes.io/version: "${VERSION}"
        azure.workload.identity/use: "true"
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: application
        image: ${DOCKER_REGISTRY}/application:${VERSION}
        ports:
        - containerPort: 3000
          name: http-port
        resources:
          requests:
            memory: "64Mi"
            cpu: "30m"
          limits:
            memory: "128Mi"
            cpu: "40m"
        startupProbe:
          exec:
            command:
            - cat
            - /proc/1/status
          periodSeconds: 10
          failureThreshold: 30
          successThreshold: 1
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - ps
            - aux
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 30
          successThreshold: 1
          timeoutSeconds: 35
        readinessProbe:
          exec:
            command:
            - ls
            - /app
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 30
          successThreshold: 1
          timeoutSeconds: 5
        imagePullPolicy: Always