apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: todo-application-deployment
  namespace: dev
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       todo-application-deployment
  updatePolicy:
    updateMode: "Off"