admissionController:
  enabled: false
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "node-1"
    effect: "NoSchedule"
  - key: "dedicated"
    operator: "Equal"
    value: "node-2"
    effect: "NoSchedule"

recommender:
  enabled: true
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "node-1"
    effect: "NoSchedule"
  - key: "dedicated"
    operator: "Equal"
    value: "node-2"
    effect: "NoSchedule"

updater:
  enabled: false
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "node-1"
    effect: "NoSchedule"
  - key: "dedicated"
    operator: "Equal"
    value: "node-2"
    effect: "NoSchedule"
