service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/load-balancer-name: istio-ingress-lb
  ports:
  - name: http2
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8443

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

serviceAccount:
  create: true
  name: istio-ingress

rbac:
  create: true

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "15020"

gateways:
  istio-ingressgateway:
    tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "node-1"
      effect: "NoSchedule"
    - key: "dedicated"
      operator: "Equal"
      value: "node-2"
      effect: "NoSchedule"

nodeSelector: {}
tolerations: []
affinity: {}
