prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: ${storage_class}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
    retention: 2d
    # resources:
    #   requests:
    #     cpu: 200m
    #     memory: 512Mi
    #   limits:
    #     cpu: 500m
    #     memory: 1Gi
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true
  persistence:
    enabled: true
    storageClass: ${storage_class}
    size: 2Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi

grafana:
  enabled: false # Using separate Grafana installation

defaultRules:
  create: true
  rules:
    alertmanager: true
    etcd: true
    configReloaders: true
    general: true
    k8s: true
    kubeApiserver: true
    kubeScheduler: true
    kubeStateMetrics: true
    kubelet: true
    node: true
    prometheus: true

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
