tempo:
  repository: grafana/tempo
  pullPolicy: IfNotPresent
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "node-1"
    effect: "NoSchedule"
  - key: "dedicated"
    operator: "Equal"
    value: "node-2"
    effect: "NoSchedule"
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 256m
      memory: 256Mi

  persistence:
    enabled: true
    storageClass: ${storage_class}
    size: 2Gi

  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
      wal:
        path: /var/tempo/wal

  serviceMonitor:
    enabled: false

  config:
    search_enabled: true
    metrics_generator_enabled: true
    server:
      http_listen_port: 3200

  multitenancy:
    enabled: false

  ingester:
    trace_idle_period: 30s
    max_block_duration: 5m
    complete_block_timeout: 5m

  compactor:
    compaction:
      block_retention: 48h 

  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
