name: Data Persistence Pipeline

on:
  push:
    paths:
    - '.github/workflows/data-persistence-pipeline.yml'
    - 'kube/storage-class.yml'
    - 'kube/mongodb-statefulset.yml'
    branches:
      - main
      - fix/*
      - feature/*
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  EKS_CLUSTER_NAME: infra-practice-dev

jobs:
  deploy-database-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHubActionsSession

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }}

      - name: Deploy Storage Class
        run: |
            kubectl apply -f kube/storage-class.yml
            kubectl get storageclass/ebs-sc

      - name: Deploy MongoDB
        run: |
          export MONGODB_USERNAME=${{ secrets.MONGODB_USERNAME }}
          export MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }}
          cat kube/mongodb-statefulset.yml | envsubst | kubectl apply -f -
          kubectl -n dev wait --for=condition=Ready pod/mongodb-0 --timeout=300s

      - name: Verify MongoDB Status
        run: |
          kubectl -n dev get pods -l app=mongodb
          kubectl -n dev get pvc -l app=mongodb